name: "CI"
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      checks: write
    env:
      RAILS_ENV: test
      CRONTOGO_ORGANIZATION_ID: "fake-crontogo-organization-id"
      CRONTOGO_API_KEY: "fake-crontogo-api-key"
    strategy:
      fail-fast: true
      matrix:
        ruby: ["3.0", "3.1", "3.2"]
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@ff740bc00a01b3a50fffc55a1071b1060eeae9dc
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Run RSpec Tests
        timeout-minutes: 20
        run: bundle exec rspec -f doc
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@ff740bc00a01b3a50fffc55a1071b1060eeae9dc
        with:
          bundler-cache: true
          ruby-version: "3.2"
      - name: Bundle Audit Check
        run: bundle exec bundle-audit update && bundle exec bundle-audit check
      - name: Setup Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: "3.10"
      - name: Run pre-commit
        uses: instrumentl/pre-commit-action@v4
