name: Release to RubyGems
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@df99e806d4462b1b0f1d13061fa63fce294b3d46
        with:
          bundler-cache: true
          ruby-version: "3.2"
      - name: Publish gem
        run: |
          umask 077
          mkdir -p "$HOME/.gem"
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
          rm -f "$HOME/.gem/credentials"
        env:
          RUBYGEMS_API_KEY: "${{secrets.RUBYGEMS_PUSH_API_KEY}}"
